### ISSUE TITLE
Infinite loop still exists for some characters

### ISSUE THREAD

**Issue by ZECTBynmo** [creationix/jsonparse#29]
See my [pull request](https://github.com/creationix/jsonparse/pull/28)

**Comment by ZECTBynmo** [comment]
@creationix IMO this is an important bug, because it brings an entire node server to it's knees, and it's difficult to find in production.

**Comment by creationix** [comment]
Thanks

**Comment by ZECTBynmo** [comment]
@creationix no problem! Can you please publish this fix to npm, so I can start working on downstream dependencies (like JSONStream) to include it? Thanks!

**Comment by creationix** [comment]
Ok, published as v1.2.0.
