### ISSUE TITLE
Allow pars escaped surrogate pairs

### ISSUE THREAD

**Issue by fiserro** [creationix/jsonparse#32]
Surrogate pairs are parsed as two 16bit chars instead of one 32bit char.
For example this Json contains two 32bit emojis:
`[ {
  "id" : "1",
  "message" : "\uD83D\uDE0B\uD83C\uDF70"
} ]`

We'r using java faster xml lib on one side https://github.com/FasterXML/jackson-core/issues/223 and nodejs jsonparse on the other side.

There is a diff with fix:
[diff.txt](https://github.com/creationix/jsonparse/files/946680/diff.txt)

**Comment by fiserro** [comment]
I can make a clean pull request. The diff is just for inspiration how to solve it.
@creationix

**Comment by creationix** [comment]
Could you please make a pull request?  Thanks.

**Comment by fiserro** [comment]
https://github.com/creationix/jsonparse/pull/33

**Comment by fiserro** [comment]
@creationix Thanks for merge https://github.com/creationix/jsonparse/pull/33. When we can expect the new version?

**Comment by creationix** [comment]
It's live!  Published to [github](https://github.com/creationix/jsonparse/releases/tag/1.3.1) and [npm](https://www.npmjs.com/package/jsonparse)
